################
### Overview ###
################

# This Cloudformation template creates the infrastructure for a simple AI chatbot.
# This application simulates a loan customer of a finance company interacting with their account. The customer can interact either using a traditional webpage or via the chatbot.
# This lab entry primarily focuses on the AI aspects of the chatbot, such as Amazon Bedrock, not the frontend code.
# If deploying in a region other than us-east-2, review code for any instances specifically referencing that region.

# Components:
# Customer Browser - runs frontend code for both the customer account page and chatbot
# Amazon Cognito - handles user authentication and JWTs; the client calls Cognito directly for authentication
# API Gateway - the primary communication point for the client; one API Gateway handles all user interaction except authentication (handled by Cognito)
# Lambda - coordinates communication among AWS services; two Lambda functions are used - one to serve frontend code (HTML/CSS/JS) and one to process chatbot functions (communicates with Bedrock)
# Bedrock - hosts the AI models used with custom guardrails
# DynamoDB - persistent storage layer for user information and AI chat messages
# CloudWatch - monitoring and logging

# User Fields in Cognito: first_name, last_name, email, username, password
# DynamoDB Tables: aws-lab-chatbot-accounts, aws-lab-chatbot-chats
# Accounts Table Fields in DynamoDB: userId (string), balance (number)
# Chats Table Fields in DynamoDB: userId (string), chatId (string), chat (string), chatReply (string)

# Improvements that should be made before this could be used as a production service:
# - Comprehensive security review of all components
# - Review for cost reduction (ie minimizing Lambda runtimes, reducing API calls)



#############
### Usage ###
#############

# Creation:
# git clone https://github.com/nevans13/aws-lab
# bash aws-lab/specific_labs/chatbot/setup.sh

# Cleanup:
# aws cloudformation delete-stack --region us-east-2 --stack-name aws-lab-chatbot
# rm -rf aws-lab



#####################
### Template Body ###
#####################

AWSTemplateFormatVersion: 2010-09-09

Description: CloudFormation template for creating infrastructure for a simple AI chatbot

Resources:
  # Amazon Cognito User Pool
  # Without the EmailConfiguration, SignInPolicy, and WebAuthnFactorConfiguration configuration, the user pool defaults to password authentication only
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: true # only an administrator can create user accounts
      DeletionProtection: INACTIVE # if set to ACTIVE, must be deactivated before the user pool can be deleted
      MfaConfiguration: "OFF" # no MFA
      Policies:
        PasswordPolicy:
          MinimumLength: 12
          PasswordHistorySize: 22
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
          RequireUppercase: true
          TemporaryPasswordValidityDays: 7
      UsernameConfiguration:
        CaseSensitive: false # usernames are not case sensitive
      UserPoolAddOns:
        AdvancedSecurityMode: "OFF" # disable activation of advanced threat protection features
      UserPoolName: aws-lab-chatbot
      UserPoolTier: ESSENTIALS # feature plan

  # The User Pool App Client represents the web application's interaction with the Cognito user pool
  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      AccessTokenValidity: 60
      ClientName: aws-lab-chatbot-frontend
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH # targeted by the browser's InitiateAuth call in the client JS
        - ALLOW_REFRESH_TOKEN_AUTH # authentication flow for token refreshes
      GenerateSecret: false # browser clients are not meant to keep a secret
      IdTokenValidity: 60
      PreventUserExistenceErrors: ENABLED # if user doesn't exist, Cognito responds with an invalid username/password error rather than a user does not exist error
      RefreshTokenValidity: 1
      TokenValidityUnits: # the units of time that AccessTokenValidity, IdTokenValidity, and RefreshTokenValidity enforce
        AccessToken: minutes
        IdToken: minutes
        RefreshToken: days
      UserPoolId: !Ref CognitoUserPool

  # This API Gateway handles all API functions for this application
  # API Gateway v2 is used for JWT support and improved performance
  APIGateway:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Description: This API Gateway handles all API functions for this application
      IpAddressType: ipv4 # only IPv4 addresses can invoke the API
      Name: aws-lab-chatbot
      ProtocolType: HTTP # use an HTTP API (versus websocket)
      Version: v1 # optional version identifier

  # The Authorizer checks authorization for specific routes; configured here to authorize based on JSON web tokens
  # On routes that use this Authorizer, API Gateway checks the validity of the JWT, including that the issuer matches the one configured here
  Authorizer:
    Type: AWS::ApiGatewayV2::Authorizer
    Properties:
      ApiId: !Ref APIGateway
      Name: aws-lab-chatbot-cognito-jwt
      AuthorizerType: JWT
      IdentitySource:
        - $request.header.Authorization
      JwtConfiguration:
        Audience:
          - !Ref CognitoUserPoolClient
        Issuer: !Sub https://cognito-idp.${AWS::Region}.amazonaws.com/${CognitoUserPool}

  # The integration between the API Gateway and the Lambda function
  APIGatewayIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref APIGateway
      IntegrationType: AWS_PROXY # this is a Lambda proxy integration between API Gateway and another AWS service
      IntegrationUri: !GetAtt FrontendLambdaFunction.Arn
      PayloadFormatVersion: "2.0"

  # Stage (deploy) the API; each stage is a named deployment of the API (prod, dev, etc)
  APIGatewayStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref APIGateway
      StageName: $default # the $default stage is served from the base of the API's URL
      AutoDeploy: true # API updates to not require an explicit redeployment of the API

  # This is the start of all the API routes on the API Gateway
  # Primary client frontend route (returns the index.html code); does not require a JWT because the user is unauthenticated when requesting the frontend code
  FrontendRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref APIGateway
      RouteKey: GET / # return index HTML code only for the root path
      Target: !Sub integrations/${APIGatewayIntegration} # the route target

  # Authenticated route to get account balance
  AccountBalanceRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref APIGateway
      AuthorizerId: !Ref Authorizer
      AuthorizationType: JWT
      RouteKey: GET /api/v1/balance
      Target: !Sub integrations/${APIGatewayIntegration}
  
  # Authenticated route to submit a new chat message to the frontend Lambda
  PostChatRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref APIGateway
      AuthorizerId: !Ref Authorizer
      AuthorizationType: JWT
      RouteKey: POST /api/v1/chat
      Target: !Sub integrations/${APIGatewayIntegration}

  # Execution role for the frontend Lambda function
  FrontendLambdaFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument: # the Trust Policy that defines which entities can assume this role
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole # Security Token Service
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole # this AWS managed policy provides write permissions to CloudWatch Logs
      Policies:
        - PolicyName: read-own-balance # this policy allows the frontend Lambda function to query the accounts table in DynamoDB
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: dynamodb:GetItem
                Resource: !GetAtt AccountsTable.Arn

  # This Lambda function handles all frontend services for this application (webpage, API, receiving message requests)
  FrontendLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Environment:
        Variables:
          ACCOUNTS_TABLE: !Ref AccountsTable # set environment variable for the DynamoDB accounts table
      FunctionName: aws-lab-chatbot-frontend
      Runtime: nodejs24.x
      Handler: index.handler
      Role: !GetAtt FrontendLambdaFunctionRole.Arn
      Timeout: 5
      MemorySize: 128
      Code:
        ZipFile: |
          exports.handler = async () => ({
            statusCode: 200,
            headers: { "Content-Type": "text/html" },
            body: "<html><body>PLEASE UPDATE CODE</body></html>"
          });

  # The AWS::Lambda::Permission resource grants an AWS service or another account permission to use a function
  FrontendInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref FrontendLambdaFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${APIGateway}/*/*

  # Execution role for the chatbot Lambda function
  ChatbotLambdaFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument: # the Trust Policy that defines which entities can assume this role
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole # Security Token Service
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole # this AWS managed policy provides write permissions to CloudWatch Logs
      Policies:
        - PolicyName: crud-chats # this policy allows the chatbot Lambda function to create, read, update, and delete the chats table in DynamoDB
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:GetItem
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
                Resource: !GetAtt ChatsTable.Arn
                Sid: AllowChatbotLambdaCrudToChatsTable
        - PolicyName: bedrock # this policy allows the chatbot Lambda function all permissions in Bedrock
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: bedrock:*
                Resource: "*"
                Sid: AllowChatbotLambdaAllBedrock

  # This Lambda function handles communication with the Bedrock AI chatbot
  # This Lambda stores chat messages in DynamoDB, interacts with Bedrock, and is called by the frontend Lambda
  ChatbotLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Environment:
        Variables:
          CHATS_TABLE: !Ref ChatsTable # set environment variable for the DynamoDB chats table
      FunctionName: aws-lab-chatbot-chatbot
      Runtime: nodejs24.x
      Handler: chatbot_function.handler
      Role: !GetAtt ChatbotLambdaFunctionRole.Arn
      Timeout: 5
      MemorySize: 128
      Code:
        ZipFile: |
          exports.handler = async () => ({
            statusCode: 200,
            headers: { "Content-Type": "text/html" },
            body: "<html><body>PLEASE UPDATE CODE</body></html>"

  # The AWS::Lambda::Permission resource grants an AWS service or another account permission to use a function
  ChatbotInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref ChatbotLambdaFunction
      Principal: lambda.amazonaws.com
      SourceArn: !GetAtt FrontendLambdaFunction.Arn # allow the frontend Lambda to call this chatbot Lambda

  # DynamoDB table for each loan account
  AccountsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: aws-lab-chatbot-accounts
      BillingMode: PAY_PER_REQUEST # no capacity planning needed for a lab-scale table
      AttributeDefinitions: # the array of attributes that make up the primary key of the table, in this case just the user ID
        - AttributeName: userId # the user ID is the value of sub (subject) from Cognito
          AttributeType: S # type is String
      DeletionProtectionEnabled: false # if set to true, must be disabled before the table can be deleted
      KeySchema: # the array of attributes that make up the primary key of the table, in this case just the user ID
        - AttributeName: userId
          KeyType: HASH # user ID is used as a partition key
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: false
      SSESpecification:
        SSEEnabled: false # server-side encryption is always enabled at rest, but with AWS owned keys (rather than admin-controlled AWS managed KMS keys)

  # DynamoDB table for chatbot chat messages
  ChatsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: aws-lab-chatbot-chats
      BillingMode: PAY_PER_REQUEST # no capacity planning needed for a lab-scale table
      AttributeDefinitions: # the array of attributes that make up the primary key of the table, in this case the chat ID
        - AttributeName: chatId # the chat ID is a GUID set by the chatbot Lambda
          AttributeType: S # type is String
      DeletionProtectionEnabled: false # if set to true, must be disabled before the table can be deleted
      KeySchema: # the array of attributes that make up the primary key of the table, in this case just the chat ID
        - AttributeName: chatId
          KeyType: HASH # chat ID is used as a partition key
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: false
      SSESpecification:
        SSEEnabled: false # server-side encryption is always enabled at rest, but with AWS owned keys (rather than admin-controlled AWS managed KMS keys)

Outputs:
  FrontendUrl:
    Description: Default execute-api URL for the frontend
    Value: !Sub https://${APIGateway}.execute-api.${AWS::Region}.amazonaws.com/

  CognitoPoolId:
    Description: The Cognito User Pool ID; used for creating a user with the AWS CLI
    Value: !Ref CognitoUserPool

  CognitoClientId:
    Description: The Cognito User Pool App Client ID; paste into ClientId in index.html
    Value: !Ref CognitoUserPoolClient